name: lol_champion_rotation
description: "LoL champion rotation checker mobile app."
publish_to: "none"
version: 1.16.0+75

environment:
  sdk: ^3.10.0

dependencies:
  async: ^2.13.0
  cached_network_image: ^3.4.1
  copy_with_extension: ^10.0.1
  dio: ^5.7.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  get_it: ^9.0.5
  intl: ^0.20.1
  json_annotation: ^4.9.0
  flutter_dotenv: ^6.0.0
  flutter_sticky_header: ^0.8.0
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  firebase_crashlytics: ^5.0.5
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  package_info_plus: ^9.0.0
  shared_preferences: ^2.3.5
  toastification: ^3.0.3
  in_app_update: ^4.2.3
  flutter_launch_store: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  build_runner: ^2.5.4
  copy_with_extension_gen: ^10.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0

flutter:
  default-flavor: development
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - CHANGELOG.md
